name: ESlint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - name: Run ESLint on all files
      run: yarn lint
    - name: Run ESLint on changed files
      run: yarn lint --fix $(git diff --name-only HEAD~1 HEAD | grep '\.js$\|\.jsx$\|\.ts$\|\.tsx$')
