name: pre-commit

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn start
      - run: yarn build
      - run: yarn test
      - run: yarn lint
      - run: yarn lint:fix
      - run: yarn prettier
